# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hawkeye < Formula
  desc "AI-powered incident investigation CLI for Neubird Hawkeye"
  homepage "https://github.com/neubirdai/hawkeye-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neubirdai/hawkeye-cli/releases/download/v0.1.0/hawkeye-0.1.0-darwin-amd64.tar.gz"
      sha256 "8285bb300eb044f9b7158ac70feb6531cf4d399db2dcdf8cf9119a78ea7dcf61"

      def install
        bin.install "hawkeye"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neubirdai/hawkeye-cli/releases/download/v0.1.0/hawkeye-0.1.0-darwin-arm64.tar.gz"
      sha256 "a83934ebe3261694596a548e9045bae425437a786497d1619ebfc2bde986b526"

      def install
        bin.install "hawkeye"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neubirdai/hawkeye-cli/releases/download/v0.1.0/hawkeye-0.1.0-linux-amd64.tar.gz"
      sha256 "b52fb62e462bf0e2c30cb021824e99f01e71e446a96a9ec4faaa01cebbb6779d"
      def install
        bin.install "hawkeye"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neubirdai/hawkeye-cli/releases/download/v0.1.0/hawkeye-0.1.0-linux-arm64.tar.gz"
      sha256 "ec1f249527503fb8b85ee6634117e1663a5f59baa99dfb61e112236f30641ed6"
      def install
        bin.install "hawkeye"
      end
    end
  end

  test do
    system "#{bin}/hawkeye", "help"
  end
end
