# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NeubirdHawkeye < Formula
  desc "AI-powered incident investigation CLI for Neubird Hawkeye"
  homepage "https://github.com/neubirdai/hawkeye-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neubirdai/hawkeye-cli/releases/download/v0.1.0/hawkeye-0.1.0-darwin-amd64.tar.gz"
      sha256 "b4353098550394b91f7241350b744d8cc12d4f388d97148b0867b02beb6fb9ab"

      def install
        bin.install "hawkeye"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neubirdai/hawkeye-cli/releases/download/v0.1.0/hawkeye-0.1.0-darwin-arm64.tar.gz"
      sha256 "a96b4a22b1a99d6bb6a4b07cdc3f30c7144f95e8ad4883757ae672544f9a314b"

      def install
        bin.install "hawkeye"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neubirdai/hawkeye-cli/releases/download/v0.1.0/hawkeye-0.1.0-linux-amd64.tar.gz"
      sha256 "a20addba2907ee5e978ea236be0a8841374fef962e0acea1dd8003b825e11aaf"
      def install
        bin.install "hawkeye"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neubirdai/hawkeye-cli/releases/download/v0.1.0/hawkeye-0.1.0-linux-arm64.tar.gz"
      sha256 "2bfd99ad1cdc7a2bd34d22432f913d92571f912f3f2908920364c5361d392dc3"
      def install
        bin.install "hawkeye"
      end
    end
  end

  test do
    system "#{bin}/hawkeye", "help"
  end
end
